### ISSUE TITLE
WebGL Runtime Error on Unity 2022.1.0a16

### ISSUE THREAD

**Issue by PTC-sradlwimmer** [Cysharp/UniTask#331]
<h1>Background: </h1>

WebGL throws multiple runtime errors trying to use UniTasks in Unity 2022

<h1>Issue: </h1>

When I reference an `UniTask` in one of my scripts the whole game crashes.
Even when the Method returning the `UniTask` isn't invoked.

I know this might be an issue with Unity 2022 only being in alpha, but I wanted to make you aware anyway

```log
exception thrown: RuntimeError: memory access out of bounds,RuntimeError: memory access out of bounds
    at il2cpp::metadata::Il2CppTypeHash::Hash(Il2CppType const*) (http://localhost:50636/Build/Build.wasm:wasm-function[916]:0x58b9e)
    at il2cpp::metadata::Il2CppGenericInstHash::operator()(Il2CppGenericInst const*) const (http://localhost:50636/Build/Build.wasm:wasm-function[917]:0x58c92)
    at dense_hashtable<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()>, KeyWrapper<il2cpp::metadata::Il2CppSignature const>, il2cpp::metadata::Il2CppSignatureHash, dense_hash_map<KeyWrapper<il2cpp::metadata::Il2CppSignature const>, void (*)(), il2cpp::metadata::Il2CppSignatureHash, KeyWrapper<il2cpp::metadata::Il2CppSignature const>::EqualsComparer<il2cpp::metadata::Il2CppSignatureCompare>, std::__2::allocator<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()> > >::SelectKey, KeyWrapper<il2cpp::metadata::Il2CppSignature const>::EqualsComparer<il2cpp::metadata::Il2CppSignatureCompare>, std::__2::allocator<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()> > >::find_position(KeyWrapper<il2cpp::metadata::Il2CppSignature const> const&) const (http://localhost:50636/Build/Build.wasm:wasm-function[26346]:0x8dce10)
    at il2cpp::vm::MetadataCache::Initialize() (http://localhost:50636/Build/Build.wasm:wasm-function[1393]:0x6f4af)
    at dynCall_i (http://localhost:50636/Build/Build.wasm:wasm-function[26585]:0x8eb095)
    at http://localhost:50636/Build/Build.framework.js:1035:20
    at invoke_i (http://localhost:50636/Build/Build.framework.js:13707:10)
    at main (http://localhost:50636/Build/Build.wasm:wasm-function[21716]:0x766f62)
    at http://localhost:50636/Build/Build.framework.js:1035:20
    at callMain (http://localhost:50636/Build/Build.framework.js:15346:13)
    at doRun (http://localhost:50636/Build/Build.framework.js:15389:21)
    at run (http://localhost:50636/Build/Build.framework.js:15401:3)
    at runCaller (http://localhost:50636/Build/Build.framework.js:15329:18)
    at Object.removeRunDependency (http://localhost:50636/Build/Build.framework.js:990:4)
    at http://localhost:50636/Build/Bui
[ColorChanger.cs.txt](https://github.com/Cysharp/UniTask/files/7625134/ColorChanger.cs.txt)
ld.framework.js:144:12
    at doCallback (http://localhost:50636/Build/Build.framework.js:4381:11)
    at done (http://localhost:50636/Build/Build.framework.js:4392:5)
    at IDBTransaction.transaction.oncomplete (http://localhost:50636/Build/Build.framework.js:3748:5)
printErr @ Build.loader.js:70


Uncaught RuntimeError: memory access out of bounds
    at il2cpp::metadata::Il2CppTypeHash::Hash(Il2CppType const*) (:50636/Build/Build.wasm)
    at il2cpp::metadata::Il2CppGenericInstHash::operator()(Il2CppGenericInst const*) const (:50636/Build/Build.wasm)
    at dense_hashtable<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()>, KeyWrapper<il2cpp::metadata::Il2CppSignature const>, il2cpp::metadata::Il2CppSignatureHash, dense_hash_map<KeyWrapper<il2cpp::metadata::Il2CppSignature const>, void (*)(), il2cpp::metadata::Il2CppSignatureHash, KeyWrapper<il2cpp::metadata::Il2CppSignature const>::EqualsComparer<il2cpp::metadata::Il2CppSignatureCompare>, std::__2::allocator<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()> > >::SelectKey, KeyWrapper<il2cpp::metadata::Il2CppSignature const>::EqualsComparer<il2cpp::metadata::Il2CppSignatureCompare>, std::__2::allocator<std::__2::pair<KeyWrapper<il2cpp::metadata::Il2CppSignature const> const, void (*)()> > >::find_position(KeyWrapper<il2cpp::metadata::Il2CppSignature const> const&) const (:50636/Build/Build.wasm)
    at il2cpp::vm::MetadataCache::Initialize() (:50636/Build/Build.wasm)
    at dynCall_i (:50636/Build/Build.wasm)
    at :50636/Build/Build.framework.js:1035
    at invoke_i (:50636/Build/Build.framework.js:13707)
    at main (:50636/Build/Build.wasm)
    at :50636/Build/Build.framework.js:1035
    at callMain (:50636/Build/Build.framework.js:15346)
    at doRun (:50636/Build/Build.framework.js:15389)
    at run (:50636/Build/Build.framework.js:15401)
    at runCaller (:50636/Build/Build.framework.js:15329)
    at Object.removeRunDependency (:50636/Build/Build.framework.js:990)
    at :50636/Build/Build.framework.js:144
    at doCallback (:50636/Build/Build.framework.js:4381)
    at done (:50636/Build/Build.framework.js:4392)
    at IDBTransaction.transaction.oncomplete (:50636/Build/Build.framework.js:3748)


Uncaught RuntimeError: memory access out of bounds
    at OrientationChangeHandler(int, int, int) (:50636/Build/Build.wasm)
    at dynCall_viii (:50636/Build/Build.wasm)
    at :50636/Build/Build.framework.js:1035
    at JS_ScreenOrientation_eventHandler (:50636/Build/Build.framework.js:1926)


Uncaught RuntimeError: memory access out of bounds
    at KeyHandler(int, EmscriptenKeyboardEvent const*, void*) (:50636/Build/Build.wasm)
    at GlobalKeyHandler(int, EmscriptenKeyboardEvent const*, void*) (:50636/Build/Build.wasm)
    at dynCall_iiii (:50636/Build/Build.wasm)
    at :50636/Build/Build.framework.js:1035
    at :50636/Build/Build.framework.js:9174
    at Object.keyEventHandlerFunc [as handlerFunc] (:50636/Build/Build.framework.js:9175)
    at jsEventHandler (:50636/Build/Build.framework.js:8071)


Uncaught RuntimeError: memory access out of bounds
    at OrientationChangeHandler(int, int, int) (:50636/Build/Build.wasm)
    at dynCall_viii (:50636/Build/Build.wasm)
    at :50636/Build/Build.framework.js:1035
    at JS_ScreenOrientation_eventHandler (:50636/Build/Build.framework.js:1926)
```

<h1>Reproduction: </h1>

1. Install `Unity 2022.1.0a16`
2. Add a cube to the empty scene
3. Add script [ColorChanger.cs](https://github.com/Cysharp/UniTask/files/7625139/ColorChanger.cs.txt)
4. Build & Run
5. Browser (Chrome) should alert an error
  `RuntimeError: memory access out of bounds`

<h1>Platforms: </h1>

Affected: `Unity 2022.1.0` - WebGL
Not Affected: `Unity 2022.1.0` - MacOS, `Unity 2021.2.2f1` - All Platforms

**Comment by PTC-sradlwimmer** [comment]
Seems to be resolved for `Unity 2022.1.0b9`
